name: Android CI/CD
on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    if: false # always skip job
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew lint

      - name: Upload lint report
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  test:
    name: Unit Test
    if: false # always skip job
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Upload test report
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: unit-test-report
          path: app/build/reports/tests/testReleaseUnitTest/

  semrel:
    name: Semantic Release
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.6.0
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.2
            conventional-changelog-conventionalcommits
            @gdn/semantic-release-native@1.3.1
            @semantic-release/exec@6.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          NPM_TOKEN: 000000000000000
  build:
    name: Build
    if: false # always skip job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.4

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt

  deploy-play-store:
    name: Build
    if: false # always skip job
    needs: [build]

    runs-on: ubuntu-latest
    steps:

      - uses: actions/download-artifact@master
        with:
          name: release.apk
      - uses: actions/download-artifact@master
        with:
          name: mapping.txt

      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}

          packageName: com.teb.quran.abrar
          releaseFiles: app-release-unsigned-signed.apk
          track: beta
          userFraction: 0.50
          mappingFile: mapping.txt